EXCERSISE- 1

1. create a 1D NumPy array containing numbers from 1 to 15.
2. Create a 2D array of shape 3×3 with numbers 1–9.
3. For arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]]), get element at row 2, col 3.
4. Get the first row of arr2D.
5. Slice last 3 elements.
6. For arr2D, get subarray containing first 2 rows and first 2 columns.
7. Convert 4×3 array to 2×6 array.
8. Reshape 1D array of 20 elements to 5×4.

In [1]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [3]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
arr = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [7]:
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
print(arr2D[1,2])

6


In [11]:
print(arr2D[1])

[4 5 6]


In [17]:
print(arr[0:12])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
# For arr2D, get subarray containing first 2 rows and first 2 columns.

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr = arr2D[:2,:2] # : from the beginning
print(arr) 

[[1 2]
 [4 5]]


In [24]:
# Convert 4×3 array to 2×6 array.
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[17,18,19]])

new_arr = arr2D.reshape(2,6)

print(new_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 17 18 19]]


In [26]:
# Reshape 1D array of 20 elements to 5×4.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

new_arr = arr.reshape(5,4)

print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


EXCERSISE -2

1. Find standard deviation and variance.
2. For arr2D = np.array([[1,2,3],[4,5,6]]), find row-wise and column-wise sum.
3. Square and square root of array [1,4,9].
4. Compute exponential of [1,2,3].
5. Compute sin, cos, tan of [0, π/2, π].
6. Generate 2×4 random integers between 0–100.
7. Set seed 42 and generate 5 random numbers.
8. Create 1D array of 10 random numbers from normal distribution.
9. Generate 7 equally spaced numbers from 2 to 14.
10. Generate 4 numbers between 0–10.
11. Compare 5 points between 0–1 using linspace vs arange.
12. Create numbers from 5–20 with step 3.
13. Create numbers from 10–1 in reverse order.
14. Create 10 numbers from 0–9 using arange.
15. Compare arange(0,2,0.3) with linspace(0,2,7).

In [2]:
import numpy as np

# 1. Find standard deviation and variance
arr = np.array([1, 2, 3, 4, 5])

print("1. Standard Deviation:", np.std(arr))
print("   Variance:", np.var(arr))

1. Standard Deviation: 1.4142135623730951
   Variance: 2.0


In [3]:
# 2. Row-wise and column-wise sum of 2D array
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("\n2. Row-wise sum:", np.sum(arr2D, axis=1))
print("   Column-wise sum:", np.sum(arr2D, axis=0))


2. Row-wise sum: [ 6 15]
   Column-wise sum: [5 7 9]


In [4]:
# 3. Square and square root of array
arr = np.array([1, 4, 9])

print("\n3. Square:", np.square(arr))
print("   Square Root:", np.sqrt(arr))


3. Square: [ 1 16 81]
   Square Root: [1. 2. 3.]


In [5]:
# 4. Exponential of [1,2,3]
arr = np.array([1, 2, 3])

print("\n4. Exponential:", np.exp(arr))


4. Exponential: [ 2.71828183  7.3890561  20.08553692]


In [6]:
# 5. Sin, Cos, Tan of [0, π/2, π]
arr = np.array([0, np.pi/2, np.pi])

print("\n5. Sin:", np.sin(arr))
print("   Cos:", np.cos(arr))
print("   Tan:", np.tan(arr))


5. Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
   Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
   Tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [20]:
# 6. Generate 2x4 random integers between 0–100
random_int = np.random.randint(0, 101, size=(2, 4))

print("\n6. Random 2x4 integers:")
print(random_int)


6. Random 2x4 integers:
[[ 8 89 52  1]
 [83 91 59 70]]


In [8]:
# 7. Set seed 42 and generate 5 random numbers
np.random.seed(42)

random_numbers = np.random.rand(5)

print("\n7. Random numbers with seed 42:")
print(random_numbers)


7. Random numbers with seed 42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [9]:
# 8. Create 1D array of 10 random numbers from normal distribution
normal_array = np.random.randn(10)

print("\n8. Normal distribution random numbers:")
print(normal_array)


8. Normal distribution random numbers:
[ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017 -0.92408284
 -2.61254901  0.95036968  0.81644508 -1.523876  ]


In [10]:
# 9. Generate 7 equally spaced numbers from 2 to 14
arr = np.linspace(2, 14, 7)

print("\n9. 7 equally spaced numbers:")
print(arr)


9. 7 equally spaced numbers:
[ 2.  4.  6.  8. 10. 12. 14.]


In [11]:
# 10. Generate 4 numbers between 0–10
arr = np.linspace(0, 10, 4)

print("\n10. 4 numbers between 0 and 10:")
print(arr)


10. 4 numbers between 0 and 10:
[ 0.          3.33333333  6.66666667 10.        ]


In [24]:
# 11. Compare 5 points between 0–1 using linspace vs arange
lin = np.linspace(0, 1, 5)
ar = np.arange(0, 1.25, 0.25)
arr = np.arange(0, 1, 5)

print("\n Linspace:")
print(lin)

print("    Arange:")
print(arr)

print("    Arange:")
print(ar)


 Linspace:
[0.   0.25 0.5  0.75 1.  ]
    Arange:
[0]
    Arange:
[0.   0.25 0.5  0.75 1.  ]


In [13]:
# 12. Create numbers from 5–20 with step 3
arr = np.arange(5, 21, 3)

print("\n12. Numbers from 5 to 20 step 3:")
print(arr)


12. Numbers from 5 to 20 step 3:
[ 5  8 11 14 17 20]


In [14]:
# 13. Create numbers from 10–1 in reverse order
arr = np.arange(10, 0, -1)

print("\n13. Reverse order:")
print(arr)


13. Reverse order:
[10  9  8  7  6  5  4  3  2  1]


In [15]:
# 14. Create 10 numbers from 0–9 using arange
arr = np.arange(10)

print("\n14. Numbers from 0 to 9:")
print(arr)


14. Numbers from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


In [16]:
# 15. Compare arange(0,2,0.3) with linspace(0,2,7)
arange_arr = np.arange(0, 2, 0.3)
linspace_arr = np.linspace(0, 2, 7)

print("\n15. arange(0,2,0.3):")
print(arange_arr)

print("    linspace(0,2,7):")
print(linspace_arr)


15. arange(0,2,0.3):
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
    linspace(0,2,7):
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]
